#!/usr/bin/env node
require("dotenv").config();

const program = require("commander");
const TwSearch = require("./twitter")({
  CONSUMER_API_KEY: process.env.CONSUMER_API_KEY,
  CONSUMER_API_SECRET: process.env.CONSUMER_API_SECRET
});

program.command("search <tag> [otherTags...]").action(function(tag, otherTags) {
  const allTags = [tag].concat(otherTags);
  console.log("looking for " + allTags.join(","));

  TwSearch(tag, 5)
    .then(tags => {
      console.dir(tags);
    })
    .catch((err, data) => {
      console.dir(err);
      console.dir(data);
    });
});

program.parse(process.argv);
